#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  encod,          sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  pushB,          sensorTouch)
#pragma config(Sensor, dgtl11, ind0,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, ind1,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           flight,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           mServL,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           mServR,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           mGate,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int sp = 45;
int del = 100;

task main() {
	while (1) {
		if (SensorValue[pushB]) {
			motor[mGate] = sp;
			sleep(del);
			motor[mGate] = 0;
			while(SensorValue[pushB]) {};
			sleep(500);
		}
	}
}
