#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  pushB,          sensorTouch)
#pragma config(Motor,  port1,           flight,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           mServL,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           mServR,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int material = 0;
task main() {
	while (1) {
		if (SensorValue[pushB]) {
			datalogDataGroupStart();
			datalogAddValue(0, material);
			datalogAddValue(1, SensorValue[lineFollower]);
			motor[flight] = -127;
			datalogAddValue(2, SensorValue[lineFollower]);
			sleep(100);
			datalogAddValue(3, SensorValue[lineFollower]);
			sleep(100);
			datalogAddValue(4, SensorValue[lineFollower]);
			motor[flight] = 0;
			datalogAddValue(5, SensorValue[lineFollower]);
			sleep(100);
			datalogAddValue(6, SensorValue[lineFollower]);
			sleep(100);
			datalogAddValue(7, SensorValue[lineFollower]);
			datalogDataGroupEnd();
			while(SensorValue[pushB]) {};
		}
	}
}
