#pragma config(Motor,  port5,           vibr,          tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (1) {}


}
