#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  encod,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  pushB,          sensorTouch)
#pragma config(Sensor, dgtl11, ind0,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, ind1,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           flight,        tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rMotorGateId,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rMotorServRId,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           rMotorServLId,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "utilities.c"
#include "indicators.c"
#include "measure.c"
#include "precalibrate.c"
#include "gate.c"

int material = -1;

task main() {
  doConfig();
  indMode[0] = 2;
  while (!SensorValue[pushB]) doIndicateTick();
  delay(100);
  while (SensorValue[pushB]) doIndicateTick();
  indMode[0] = 2;
  indMode[0] = 0;
  precalibrate();
  indMode[0] = 0;
  indMode[1] = 3;
  while (1) {
    indMode[1] = 3;
    indMode[0] = 1;
    // while (!SensorValue[pushB]) doIndicateTick();
    // delayInd(100);
    // while (SensorValue[pushB]) doIndicateTick();

    delayInd(CONFIG.SORT_DELAY);

    indMode[1] = 4;
    indMode[0] = 1;

    material = getMaterial();

    if (material == -1) {
      return;
    }

    switch (material) {
      case 0:
        mgate = -CONFIG.GATE_SPEED;
        msl = CONFIG.SERVO_PATH_LEFT;
        break;
      case 1:
        mgate = -CONFIG.GATE_SPEED;
        msl = CONFIG.SERVO_PATH_RIGHT;
        break;
      case 2:
        mgate = CONFIG.GATE_SPEED;
        msr = CONFIG.SERVO_PATH_LEFT;
        break;
      case 3:
        mgate = CONFIG.GATE_SPEED;
        msr = CONFIG.SERVO_PATH_RIGHT;
        break;
      default:
        return;
    }
    delayInd(CONFIG.GATE_LENGTH);
    if (material > 1) {
      // do a quick hop back the other way -
      // this should help get the sensor in a better place each time.
      mgate = -100;
      delayInd(50);
      mgate = 0;
    }
    goToZero();
  }
}
